server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

grpc:
  client:
    GLOBAL:
      negotiationType: plaintext

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka