server:
  port: 8080

spring:
  application:
    name: gateway-service

grpc:
  client:
    GLOBAL:
      negotiationType: plaintext

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka