server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  client:
    # Don't register Eureka server in itself
    # It allows to start without exceptions
    register-with-eureka: false
    fetch-registry: false
    instance:
      hostname: localhost