server:
  port: 0

spring:
  application:
    name: team-service
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: teams
      port: 27017
      host: localhost
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

grpc:
  server:
    port: 0

bootstrapAddress: localhost:9092