server:
  port: 0

spring:
  application:
    name: team-service
  data:
    mongodb:
      authentication-database: admin
      username:
      password:
      database: team-specs
      port: 27017
      host: localhost
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

grpc:
  cloud-grpc-server:
    address: 'discovery://api-gateway'
    enableKeepAlive: true
    keepAliveWithoutCalls: true
    negotiationType: plaintext
  server:
    port: 0